version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: web
      APP_PORT: 3000

  web:
    image: ghcr.io/21mcom/watchtower:1.0.0
    restart: on-failure
    stop_grace_period: 1m
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://watchtower:watchtower@db:5432/watchtower
    depends_on:
      - db
    networks:
      - default

  db:
    image: postgres:16-alpine
    restart: on-failure
    stop_grace_period: 1m
    environment:
      POSTGRES_USER: watchtower
      POSTGRES_PASSWORD: watchtower
      POSTGRES_DB: watchtower
    volumes:
      - ${APP_DATA_DIR}/postgres:/var/lib/postgresql/data
    networks:
      - default

networks:
  default: {}
